# Generated by Django 4.2.11 on 2024-05-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='firstName')),
                ('surname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='surname')),
                ('patronymic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='patronymic')),
                ('role_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userAccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('vector_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Vector Id')),
                ('iin', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='iin')),
                ('firstname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='firstName')),
                ('surname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='surname')),
                ('patronymic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='patronymic')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('photo', models.TextField(verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata instances',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchedPhoto', models.TextField(verbose_name='Photo')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='metadata.account')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
