# Generated by Django 4.2.11 on 2024-05-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('vector_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Vector Id')),
                ('photo', models.TextField(verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery instances',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='iin')),
                ('firstname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='firstName')),
                ('surname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='surname')),
                ('patronymic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='patronymic')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person instances',
            },
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.AddField(
            model_name='gallery',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.person'),
        ),
    ]
