# Generated by Django 4.2.15 on 2024-08-19 15:27

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_gallery_person_delete_metadata_gallery_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('criminal_case', 'Criminal case'), ('investigative_orders', 'Investigative orders'), ('prosecutor_instructions', 'Prosecutor instructions'), ('international_orders', 'International orders'), ('afm_orders', 'Afm orders'), ('head_orders', 'Head orders'), ('operational_inspections', 'Operational inspections'), ('analytical_work', 'Analytical work')], max_length=500, null=True, verbose_name='Search Reason'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='reason_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True, verbose_name='Reason Data'),
        ),
        migrations.CreateModel(
            name='ProsecutorInstructionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='prosecutor order number')),
                ('order_date', models.DateField(verbose_name='prosecutor order date')),
                ('document_number', models.CharField(max_length=255, verbose_name='prosecutor document number')),
                ('check_list', models.CharField(max_length=255, verbose_name='prosecutor check list')),
                ('other_reason', models.CharField(max_length=255, verbose_name='prosecutor other reason')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prosecutor_order_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalInspectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere_name', models.CharField(max_length=255, verbose_name='sphere name')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_inspection_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigativeOrderReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='Investigative order number')),
                ('order_date', models.DateField(verbose_name='Investigative order date')),
                ('document_number', models.CharField(max_length=255, verbose_name='Investigative document number')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigative_order_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalOrderReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='international order number')),
                ('order_date', models.DateField(verbose_name='international order date')),
                ('organisation', models.CharField(max_length=255, verbose_name='international organisation')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_order_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOrderReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='head order number')),
                ('order_date', models.DateField(verbose_name='head order date')),
                ('head_fio', models.CharField(max_length=255, verbose_name='head fio')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_order_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalCaseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='Order number')),
                ('order_date', models.DateField(verbose_name='Order date')),
                ('order_article', models.CharField(max_length=255, verbose_name='Order article')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_case_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticalWorkReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='analytical work theme')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytical_work_reason', to='metadata.searchhistory')),
            ],
        ),
        migrations.CreateModel(
            name='AfmOrderReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='afm order number')),
                ('order_date', models.DateField(verbose_name='afm order date')),
                ('search_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afm_order_reason', to='metadata.searchhistory')),
            ],
        ),
    ]
