# Generated by Django 4.2.15 on 2024-08-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_searchhistory_reason_searchhistory_reason_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afmorderreason',
            options={'verbose_name': 'AfmOrderReason', 'verbose_name_plural': 'AfmOrderReasons'},
        ),
        migrations.AlterModelOptions(
            name='analyticalworkreason',
            options={'verbose_name': 'AnalyticalWorkReason', 'verbose_name_plural': 'AnalyticalWorkReasons'},
        ),
        migrations.AlterModelOptions(
            name='criminalcasereason',
            options={'verbose_name': 'CriminalCaseReason', 'verbose_name_plural': 'CriminalCaseReasons'},
        ),
        migrations.AlterModelOptions(
            name='headorderreason',
            options={'verbose_name': 'HeadOrderReason', 'verbose_name_plural': 'HeadOrderReasons'},
        ),
        migrations.AlterModelOptions(
            name='internationalorderreason',
            options={'verbose_name': 'InternationalOrderReason', 'verbose_name_plural': 'InternationalOrderReasons'},
        ),
        migrations.AlterModelOptions(
            name='investigativeorderreason',
            options={'verbose_name': 'InvestigativeOrderReason', 'verbose_name_plural': 'InvestigativeOrderReasons'},
        ),
        migrations.AlterModelOptions(
            name='operationalinspectionreason',
            options={'verbose_name': 'OperationalInspectionReason', 'verbose_name_plural': 'OperationalInspectionReasons'},
        ),
        migrations.AlterModelOptions(
            name='prosecutorinstructionreason',
            options={'verbose_name': 'ProsecutorInstructionReason', 'verbose_name_plural': 'ProsecutorInstructionReasons'},
        ),
        migrations.AlterField(
            model_name='prosecutorinstructionreason',
            name='check_list',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='prosecutor check list'),
        ),
        migrations.AlterField(
            model_name='prosecutorinstructionreason',
            name='other_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='prosecutor other reason'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('CRIMINAL_CASE', 'Criminal case'), ('INVESTIGATIVE_ORDERS', 'Investigative orders'), ('PROSECUTOR_INSTRUCTIONS', 'Prosecutor instructions'), ('INTERNATIONAL_ORDERS', 'International orders'), ('AFM_ORDERS', 'Afm orders'), ('HEAD_ORDERS', 'Head orders'), ('OPERATIONAL_INSPECTIONS', 'Operational inspections'), ('ANALYTICAL_WORK', 'Analytical work')], max_length=500, null=True, verbose_name='Search Reason'),
        ),
    ]
