# Generated by Django 4.2.15 on 2024-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_alter_afmorderreason_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='reason_data',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('CRIMINAL_CASE', 'Criminal case'), ('INVESTIGATIVE_ORDER', 'Investigative orders'), ('PROSECUTOR_INSTRUCTION', 'Prosecutor instructions'), ('INTERNATIONAL_ORDER', 'International orders'), ('AFM_ORDER', 'Afm orders'), ('HEAD_ORDER', 'Head orders'), ('OPERATIONAL_INSPECTION', 'Operational inspections'), ('ANALYTICAL_WORK', 'Analytical work')], max_length=500, null=True, verbose_name='Search Reason'),
        ),
    ]
