# Generated by Django 4.2.23 on 2025-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_account_created_at_account_face_vector_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='context',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Context'),
        ),
    ]
